### ISSUE TITLE
CRF parameters for all 23 categories

### ISSUE THREAD

**Issue by madhawav** [keunhong/kitnn#4]
Hi, 
How did you acquire CRF parameters for the 5 categories fabric, leather, wood, metal, plastic and background? Do you have the CRF parameters for all 23 categories of MNC? 

Please share if you do.

**Comment by keunhong** [comment]
Hi, I set them manually. I believe the CRF parameters for those materials are available in the supplemental materials of the original materials in context paper.

**Comment by madhawav** [comment]
Yes, they are available. Linking the document for anyone else who may refer to this conversation: http://labelmaterial.s3.amazonaws.com/release/cvpr2015-minc-supp.pdf

Thank you!
